channels:
  - conda-forge
dependencies:
  - python=3.10
  - xarray
  - netcdf4
  - h5netcdf
  - hdf5
  - cftime
  - numpy
  - pandas
  - geopandas
  - matplotlib
  - cmocean
  - cartopy
  - shapely
  - pyproj

